version: '2'
services:
    mutuplex-app:
        image: mutuplex
        external_links:
            - mutuplex-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/mutuplex
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mutuplex-postgresql:
        extends:
            file: postgresql.yml
            service: mutuplex-postgresql
